---
title: Introduction à Git
author: Bervelin Lumesa
date: '2024-02-25'
slug: []
categories:
  - Git
tags:
  - Version control
comments: yes
description: ''
images:
  - alt: ''
    src: 'https://git-scm.com/images/logos/downloads/Git-Logo-2Color.png'
    stretch: ''
removeBlur: no
---


# Introduction

Dans le monde du développement de logiciels, développement web, la science de données ou dans la programmation de façon générale, la gestion des versions est essentielle pour maintenir un code propre et évolutif. 

Git est un système de contrôle de version largement utilisé qui permet aux développeurs, data scientists et autres scientifiques de collaborer efficacement sur des projets en travaillant sur un code commun. 

GitHub, quant à lui, est une plateforme de développement collaboratif basée sur Git, offrant des fonctionnalités supplémentaires telles que le suivi des problèmes, le déploiement, l'intégration continue et bien plus encore.

Dans cet article, nous allons explorer les concepts de base de Git et GitHub, et comment les utiliser pour gérer efficacement votre code.

# A la découverte de Git

## Qu'est-ce que Git ?

Git est un système de contrôle de version distribué, conçu pour gérer tout projet, petit ou grand, avec rapidité et efficacité. Il permet de suivre les modifications apportées aux fichiers, de revenir à des versions précédentes, de fusionner des branches et bien plus encore. Voici quelques termes de base que vous devez connaître :

- **Repository (dépôt)** : Un dépôt Git est un espace de stockage où votre projet et son historique sont conservés.

- **Commit (validation)** : Un commit est une sauvegarde de vos modifications dans le dépôt Git.

- **Branch (branche)** : Une branche est une version alternative de votre code. Elle permet de travailler sur des fonctionnalités ou des correctifs sans affecter la branche principale (habituellement appelée `main` ou `master`). Imaginer que votre équipe traille sur un projet et que vous êtes charger d'ajouter une nouvelle fonctionnalité. Il serait prudent de travailler sur une branche indépendante, qui pourra être révisée et fusionnée avec le code principal.

- **Merge (fusion)** : La fusion est le processus de combiner les modifications de deux branches différentes en une seule.

## Installation de Git

Pour commencer à utiliser Git, vous devez d'abord l'installer sur votre ordinateur. Vous pouvez télécharger Git à partir du site officiel [git-scm.com](https://git-scm.com/downloads) et suivre les instructions d'installation spécifiques à votre système d'exploitation.

## Configuration de Git

Après avoir installé Git, vous devez configurer votre nom d'utilisateur et votre adresse e-mail. Vous pouvez le faire en exécutant les commandes suivantes dans votre terminal :

```bash
git config --global user.name "Votre Nom"
git config --global user.email "votre@email.com"
```

## Création d'un nouveau dépôt Git

Pour créer un nouveau dépôt Git pour votre projet local, naviguez vers le répertoire de votre projet dans le terminal et exécutez la commande suivante :

```bash
git init
```

Cela initialisera un nouveau dépôt Git dans le répertoire actuel.

## Ajout et validation de fichiers

Une fois votre dépôt initialisé, vous pouvez commencer à ajouter des fichiers à suivre et à valider. Utilisez la commande `git add` pour ajouter des fichiers à l'index et la commande `git commit` pour valider les modifications. Voici un exemple :

```bash
git add fichier1.txt fichier2.txt
git commit -m "Premier commit : Ajout de fichiers de base"
```

Il est important d'ajouter un commentaire qui donne une idée de la modification apportée.

## Création d'une branche

Lorsque vous travaillez sur une nouvelle fonctionnalité ou un correctif, il est recommandé de créer une nouvelle branche pour isoler vos modifications. Vous pouvez le faire en utilisant la commande suivante :


```bash
git checkout -b nouvelle-branche
```

Cela créera une nouvelle branche et vous basculera automatiquement dessus.

## Fusion de branches

Une fois que vous avez terminé de travailler sur votre fonctionnalité ou votre correctif, vous pouvez fusionner votre branche avec la branche principale en utilisant la commande `git merge`. Voici un exemple :


```bash
git checkout main
git merge nouvelle-branche
```

Cela fusionnera les modifications de votre nouvelle branche dans la branche principale.

NB : La commande `git checkout main` permet de revenir à la branche principale (main).


# Utilisation de GitHub

Maintenant que vous avez appris les bases de Git, vous pouvez utiliser GitHub pour héberger votre code et collaborer avec d'autres développeurs ou data scientists. Avec GitHub, vous pouvez travailler sur le même code avec des développeurs se trouvant à l'autre bout du monde.

Voici quelques étapes pour commencer :

1. Créez un compte sur GitHub en [cliquant ici](https://github.com/).
2. Créez un nouveau dépôt sur GitHub.
3. Liez votre dépôt local Git à votre dépôt GitHub en utilisant les commandes suivantes sur Git :

```bash
git remote add origin <url_de_votre_depot_github>
git push -u origin main
```

Cela ajoutera votre dépôt GitHub comme un dépôt distant et poussera vos modifications locales vers GitHub.

La commande `git push -u origin main` permet d'envoyer votre code local vers votre dépôt distant sur GitHub.

Maintenant, vous pouvez collaborer avec d'autres développeurs en détectant des problèmes, des demandes d'extraction et en fusionnant des contributions.

# Conclusion

Git et GitHub sont des outils puissants pour gérer efficacement le développement de logiciels en équipe. En comprenant les concepts de base de Git et en utilisant GitHub, vous serez en mesure de suivre l'évolution de votre code, de collaborer avec d'autres développeurs et de livrer des projets de haute qualité.


Ce post vous a-t-il plu? N'oubliez pas de le partager autour de vous!

_TO KUTANI MBALA YA SIMA :)_

